

      <div class="starter-template">
        <h1>Quer compartilhar algo interessante?</h1>
        <p class="lead">Informe abaixo, em até 140 caracteres ;-)</p>
        <div class="col-md-12">
            <form action="#">
                <div class="form-group">
                    <textarea class="form-control post-content" rows="4"></textarea>
                </div>
                <div class="text-right">
                    <button type="button" class="btn btn-large btn-success pull-right" onClick="postar()">Postar</button><div id="remain" class="pull-right red"></div>
                </div>
            </form>
        </div>
        

        <p class="lead">Veja o que está sendo falado neste momento.</p>
        <div class="loading hide"><img src="img/loading.gif" alt="Aguarde..."></div>

        <div class="col-md-12">
            <div class="posts">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1>:/</h1>
                        <p>Parece que nada foi dito até agora...</p>
                    </div>
                </div>
            </div>
        </div>

      </div>


        <script>
            var timeObj = null;
            var iLastPostId = null;
            var iTimeLimitReload = 5;
            
            function onload() {
              
                var maxchars = 140;
                $('.post-content').keyup(function () {
                    var tlength = $(this).val().length;
                    $(this).val($(this).val().substring(0, maxchars));
                    var tlength = $(this).val().length;
                    remain = maxchars - parseInt(tlength);
                    $('#remain').text(remain);
                    if ((remain)<20) {
                        $('#remain').addClass('red');
                    }
                    else {
                        $('#remain').removeClass('red');
                    }
                });
              
                loading();
                WSRestGet('/Microblog/getAllActivePosts', catchJson, 5000, false);
            }
        </script>